commerce_payment.commerce_payment_gateway.plugin.turtlecoin_payment_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    turtlecoin_address_store:
      type: string
      label: 'TurtleCoin address'
    wallet_api_host:
      type: string
      label: 'The host where your wallet-api is available.'
    wallet_api_port:
      type: string
      label: 'The port where your wallet-api is available.'
    wallet_api_password:
      type: string
      label: 'The password the wallet-api uses to authorize.'

commerce_payment.commerce_payment_type.plugin.payment_turtle_coin:
  type: commerce_payment_type_configuration
  mapping:
    turtle_coin_integrated_address:
      type: string
      label: 'Integrated address'
    turtle_coin_block_index:
      type: integer
      label: 'Block Index'