commerce_payment.commerce_payment_gateway.plugin.turtlecoin_payment_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    turtlecoin_address_store:
      type: string
      label: 'TurtleCoin address which will receive the payments.'
    wallet_api_host:
      type: string
      label: 'The host where your turtle-service is available.'
    wallet_api_port:
      type: string
      label: 'The port where your turtle-service is available.'
    wallet_api_password:
      type: string
      label: 'The password the turtle-service uses to authorize.'
    wait_for_transactions_time:
      type: number_integer
      label: 'The time we should wait for a transaction until it is marked as voided, in seconds.'

commerce_payment.commerce_payment_gateway.plugin.turtlepay_payment_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    turtlecoin_address_store:
      type: string
      label: 'TurtleCoin address which will receive the payments.'
    turtlepay_callback_host:
      type: string
      label: 'The host to use for the incoming TurtlePay status updates.'
