commerce_payment.commerce_payment_gateway.plugin.turtlecoin_payment_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    turtlecoin_address_store:
      type: string
      label: 'TurtleCoin address'